# Your CurseForge API key goes here.
# Only required if using CurseForge links.
# To get an API key:
#   Go to https://console.curseforge.com/?#/api-keys
#   Sign in
#   Close the pop up in the middle of the screen
#   Click API keys on the left
#   Copy paste the key into the CurseForge API Key field after the :
CurseForge API Key: REPLACE_THIS_WITH_YOUR_API_KEY

# Option for enabling/disabling update checking. true or false (no capitals)
Check for RMMUD Updates: false

# Folder location for downloading  mods into. Can be relative or absolute.
Downloads Folder: RMMUDDownloads

# Folder location that contains instance files. Can be relative or absolute.
Instances Folder: RMMUDInstances
